include::global.adoc[]
= GitHub Flavored Asciidoc (GFA)
ifdef::env-github[]

:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:

:imagesdir: images/
:userid: siduser###
:userpassword: sid
:jumphost: jump.mysidlabs.com
:jumphostname: jump
:prompt: {userid}@{jumphostname}:~$ 
:icons:

endif::[]
:toc:
:toc-placement!:

=== Ansible Lab 1 - Ansible Command Line
==== Overview
This is a quick lab meant to be run from the command line.
You will perform the following tasks in the course of this exercise:

. Provision an AWS EC2 instance
. Minimally configure the instance once it has been provisioned.
. Log into the instance once configuration is complete to take a look around.
. Clean up, de-provisioning the instance once the lab is complete.

==== Lab 1
. The lab will be run from a bastion host in AWS. Begin by SSHing to the jump host with the command:
+
[source,bash]
[subs="verbatim,attributes"]
----
$> ssh <siduser###>@jump.mysidlabs.com 
----
+
Where `<siduser###>` is the user id provided by your instructor and using the password `{userpassword}`.


. Once connected, `cd` into the `dev/ansible/lab1-windows` directory and review it's contents.
+
[source,bash]
[subs="verbatim,attributes"]
----
$> tree
lab1-windows
├── ansible.cfg
├── clean.yaml
├── configure.yaml
├── create.yaml
├── group_vars
│   └── all.yaml
└── login
----
* https://github.com/mysidlabs/ansible-labs/blob/master/lab1/ansible.cfg[*ansible.cfg*] - this is a local ansible config file which overrides some aspects of the global  `/etc/ansible/ansible.cfg` file.
+
[source,cfg]
----
[defaults]
host_key_checking = False

[colors]
verbose=normal
----
+
* https://github.com/mysidlabs/ansible-labs/blob/master/lab1/group_vars/all.yaml[*group_vars/all.yaml*] - this file defines variables that can be applied against groups defined in the inventory.
In this case the filename _all.yaml_ represents the special _Ansible_ defined group `*_all_*` which will affect every host in the inventory.
Group variables provide a method to cross-cut concerns when provisioning infrastructure.
More information on inventory, host, and group variables can be found https://docs.ansible.com/ansible/latest/user_guide/intro_inventory.html[here].
+
For this lab, the Administrator account and password are stored as variables in this file.  Therefore it has been encrypted using ansible-vault.  To view the file on the cli, view the file using the following command:
+
`ansible-vault edit group_vars/all.yaml` and then enter your lab password when prompted.
+
[source,yaml]
----
---
ansible_user: Administrator
ansible_password: wind0wsSidlabs!
user_password: Ger2014!
ansible_connection: winrm
ansible_winrm_server_cert_validation: ignore
ansible_winrm_transport: basic

# ansible_python_interpreter: "auto_silent"
# ansible_ssh_private_key_file: "~/.ssh/ssh-key.pem"

inventory_file: "inv.txt"
siduser: "{{ lookup('env', 'USER') | default('siduser299', true) }}"

# AWS
# aws_ssh_key_pair: "ansible-labs-only"
instance_type: "t3a.medium"
region: "us-east-2"
security_group: "ansible-winrm-enabled"
vpc_subnet: "subnet-3964a275"
...

----

[NOTE] 
====
By default ansible vault uses VI as a text editor, to exit VI text editor use :q!
====


* https://github.com/mysidlabs/ansible-labs/blob/master/lab1/create.yaml[*create.yaml*] - this is a simple _Ansible_ playbook that creates an AWS ec2 instance and then dynamically creates an inventory file, inv.txt with the newly created host as the only entry.  Also note that the the target host for this play is *_localhost_*.
+
[source,yaml]
----
---
# Step 1 - Create a single EC2 instance and boot it.
# No configuration beyond a simple boot will be done.

- name: "Create host instance"
  hosts: localhost
  gather_facts: false

  tasks:

    - name: "Provision and launch instances"
      ec2:
        assign_public_ip: true
        group: "{{ security_group }}"
        image: "ami-01e36b7901e884a10"
        instance_tags:
          Name: "{{ siduser }}-lab1"
          mysidlabs: "1"
          mysidlabs_owner: "{{ siduser }}"
          mysidlabs_tier: "lab1"
        instance_type: "{{ instance_type }}"
        key_name: "{{ aws_ssh_key_pair }}"
        region: "{{ region }}"
        vpc_subnet_id: "{{ vpc_subnet }}"
        wait: true
      register: ec2

    # Create an Ansible inventory file that contains
    # the public DNS name of the instance just created.
    - name: "Remove old host inventory file"
      file:
        path: "hosts"
        state: absent
    - name: "Create hosts inventory file"
      lineinfile:
        create: true
        path: "inv.txt"
        line: "{{ ec2.instances[0].public_dns_name }}"

    - debug:
        msg: "{{ ec2.instances[0].tags.Name }} == Private IP: {{ ec2.instances[0].private_ip }}, Public IP: {{ ec2.instances[0].public_ip }}"
      
...
----
* https://github.com/mysidlabs/ansible-labs/blob/master/lab1/configure.yaml[*configure.yaml*] - this play configures the host. It creates a user account, distributes an ssh-key, and then installs a few basic packages.
+
[source,yaml]
----
---
  
# Step 2 - Configure the instance.  This is a simple
# example that just creates a user acct and installs IIS and management tools.
#  This playbook can be extended to do more detailed configuration.

- name: "Configure Instance"
  hosts: all
  gather_facts: true

  tasks:

    - name: "Ensure User Account Exists"
      win_user:
        name: "{{ siduser }}"
        password: "{{ user_password }}"
        groups: Administrators

    - name: Install IIS Web-Server with sub features and management tools
      win_feature:
        name: web-server
        state: present
        include_sub_features: yes
        include_management_tools: yes
      register: win_feature

    - name: Reboot if installing Web-Server feature requires it
      win_reboot:
      when: win_feature.reboot_required

...
----



. After reviewing the files we want to begin by executing the initial play defined in _create.yaml_.
+
[source,bash]
[subs="verbatim,attributes"]
----
$> ansible-playbook create.yaml --ask-vault-pass
----
+
If the play is successful you will see output as the playbook executes ending with something similar to the following:
+
[source,ansible]
----
...

TASK [debug] ******************************************************************************************************
ok: [localhost] => {
    "msg": "siduser298-lab1 == Private IP: 172.31.36.33, Public IP: 18.189.29.52"
}

PLAY RECAP ******************************************************************************************************
localhost                  : ok=4    changed=2    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
----
+
The debug statement returns the public and private IPs of the newly created host which has also been written to the inv.txt local inventory file mentioned above.

. Now that the host is available the _configure.yaml_ play can be run to make the instance slightly more useful.
Execute the _configure.yaml_ play with the following command using the `-i` flag to specify the _inv.txt_ as the inventory source for this _Ansible_ run:
+
[source,bash]
[subs="verbatim,attributes"]
----
$> ansible-playbook configure.yaml -i inv.txt --ask-vault-pass
----
+
In the event that a play does not complete successfully, the output will return with a an error and provide the error message returned by the failed process on the target host.

+
[source,ansible]
[subs="verbatim,attributes"]
----
PLAY [Configure Instance] **************************************************************************************************************************************

TASK [Gathering Facts] *****************************************************************************************************************************************
ok: [ec2-3-18-225-194.us-east-2.compute.amazonaws.com]

TASK [Ensure User Account Exists] ******************************************************************************************************************************
ok: [ec2-3-18-225-194.us-east-2.compute.amazonaws.com]

TASK [Install IIS Web-Server with sub features and management tools] *******************************************************************************************
ok: [ec2-3-18-225-194.us-east-2.compute.amazonaws.com]

TASK [Reboot if installing Web-Server feature requires it] *****************************************************************************************************
skipping: [ec2-3-18-225-194.us-east-2.compute.amazonaws.com]

PLAY RECAP *****************************************************************************************************************************************************
ec2-3-18-225-194.us-east-2.compute.amazonaws.com : ok=3    changed=3    unreachable=0    failed=0    skipped=1    rescued=0    ignored=0   
----
In this example we can see that 3 tasks were executed, 3 were ok, 2 changed and 1 skipped.

. Now you can connect to the host by via rdp if you have a client available.  Use the dns name visible in the output from the previous configure play run and then login
using your sidlab user-name and the lab password that was provided.  You can then launch inetmgr from the run box on the server and verify that IIS and the management
have been installed.
+
// [source,bash]
// [subs="verbatim,attributes"]
// ----
// $> ./login
// ----
// Once connected, verify that the packages specified in the _configure.yaml_ play are now available on the target host. e.g.
// +
// [source,bash]
// [subs="verbatim,attributes"]
// ----
// [siduser270@ip-172-31-45-143 ~]$ git --version
// git version 1.8.3.1
// [siduser270@ip-172-31-45-143 ~]$ 

// [siduser270@ip-172-31-45-143 ~]$ wget www.google.com
// --2020-05-27 16:36:46--  http://www.google.com/
// Resolving www.google.com (www.google.com)... 172.217.4.36, 2607:f8b0:4009:804::2004
// Connecting to www.google.com (www.google.com)|172.217.4.36|:80... connected.
// HTTP request sent, awaiting response... 200 OK
// Length: unspecified [text/html]
// Saving to: 'index.html'

//     [ <=>                                                                                                                   ] 12,016      --.-K/s   in 0s      

// 2020-05-27 16:36:47 (128 MB/s) - 'index.html' saved [12016]

// [siduser270@ip-172-31-45-143 ~]$ vim index.html 

// ...
// output truncated
// ...

// ----


. Finally, run the _clean.yaml_ play to destroy the ec2 instances and clean up the environment.
+
[source,bash]
[sub="verbatim,attributes"]
----
siduser270@toolkit ~/dev/ansible/lab1 # ansible-playbook clean.yaml 
[WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'

PLAY [Cleanup all instances that match the target tag - mysidlabs_owner: {{ siduser }}] ************************************************************************

TASK [Terminate labeled instances] *****************************************************************************************************************************
changed: [localhost]

TASK [Delete stale hosts inventory file] ***********************************************************************************************************************
changed: [localhost]

PLAY RECAP *****************************************************************************************************************************************************
localhost                  : ok=2    changed=2    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   

siduser270@toolkit ~/dev/ansible/lab1 # 

----

