include::global.adoc[]
= GitHub Flavored Asciidoc (GFA)
ifdef::env-github[]

:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:

:imagesdir: images/
:userid: siduser###
:userpassword: sid
:jumphost: jump.mysidlabs.com
:jumphostname: jump
:prompt: {userid}@{jumphostname}:~$ 
:icons:

endif::[]
:toc:
:toc-placement!:

=== Ansible Lab 1 - Ansible Command Line
==== Overview
This is a quick lab meant to be run from the command line.
You will perform the following tasks in the course of this excercise:

. Provision an AWS EC2 instance
. Minimaly configure the instance once it has been provisioned.
. Log into the instance once configuration is complete to take a look around.
. Clean up, deprovisioning the instance once the lab is complete.

==== Lab 1
. The lab will be run from a bastion host in AWS. Begin by SSHing to the jump host with the command:
+
[source,bash]
[subs="verbatim,attributes"]
----
$> ssh <siduser###>@jump.mysidlabs.com 
----
+
Where `<siduser###>` is the user id provided by your instructor and using the password `{userpassword}`.


. Once connected, `cd` into the `dev/ansible-labs/lab1` directory and review it's contents.
+
[source,bash]
[subs="verbatim,attributes"]
----
$> tree
lab1
├── ansible.cfg
├── clean.yaml
├── configure.yaml
├── create.yaml
├── group_vars
│   └── all.yaml
└── login
----
* https://github.com/mysidlabs/ansible-labs/blob/master/lab1/ansible.cfg[*ansible.cfg*] - this is a local ansible config file which overrides some aspects of the global  `/etc/ansible/ansible.cfg` file.
+
[source,cfg]
----
[defaults]
host_key_checking = False
ansible_python_interpreter=/usr/bin/python3

[colors]
verbose=normal
----
+
* https://github.com/mysidlabs/ansible-labs/blob/master/lab1/group_vars/all.yaml[*group_vars/all.yaml*] - this file defines variables that can be applied against groups defined in the inventory.
In this case the filename _all.yaml_ represents the special _Ansible_ defined group `*_all_*` which will affect every host in the inventory.
Group variable provide a method to cross-cut concerns when provisioning infrastructure.
More information on inventory, host, and group variables can be found https://docs.ansible.com/ansible/latest/user_guide/intro_inventory.html[here].
+
[source,yaml]
----
 ---
ansible_user: "centos"
ansible_python_interpreter: "auto_silent"
ansible_ssh_private_key_file: "~/.ssh/ssh-key.pem"

inventory_file: "inv.txt"
siduser: "{{ lookup('env', 'USER') | default('siduser299', true) }}"

# AWS 
aws_ssh_key_pair: "ansible-labs-only"
instance_type: "t2.micro"
region: "us-east-2"
security_group: "ssh-http-https"
vpc_subnet: "subnet-3964a275"
...
----
+
* https://github.com/mysidlabs/ansible-labs/blob/master/lab1/create.yaml[*create.yaml*] - this is a simple _Ansible_ playbook that creates an AWS ec2 instance and then dynamically creates an inventory file, inv.txt with the newly created host as the only entry.  Also note that the the target host for this play is *_localhost_*.
+
[source,yaml]
----
---
# Step 1 - Create a single EC2 instance and boot it.
# No configuration beyond a simple boot will be done.

- name: "Create host instance"
  hosts: localhost
  gather_facts: false

  tasks:

    - name: "Provision and launch instances"
      ec2:
        assign_public_ip: true
        group: "{{ security_group }}"
        image: "ami-01e36b7901e884a10"
        instance_tags:
          Name: "{{ siduser }}-lab1"
          mysidlabs: "1"
          mysidlabs_owner: "{{ siduser }}"
          mysidlabs_tier: "lab1"
        instance_type: "{{ instance_type }}"
        key_name: "{{ aws_ssh_key_pair }}"
        region: "{{ region }}"
        vpc_subnet_id: "{{ vpc_subnet }}"
        wait: true
      register: ec2

    # Create an Ansible inventory file that contains
    # the public DNS name of the instance just created.
    - name: "Remove old host inventory file"
      file:
        path: "hosts"
        state: absent
    - name: "Create hosts inventory file"
      lineinfile:
        create: true
        path: "inv.txt"
        line: "{{ ec2.instances[0].public_dns_name }}"

    - debug:
        msg: "{{ ec2.instances[0].tags.Name }} == Private IP: {{ ec2.instances[0].private_ip }}, Public IP: {{ ec2.instances[0].public_ip }}"
      
...
----
* https://github.com/mysidlabs/ansible-labs/blob/master/lab1/configure.yaml[*configure.yaml*] - this play configures the host. It creates a user account, distributes an ssh-key, and then installs a few basic packages.
+
[source,yaml]
----
---
# Step 2 - Configure the instance.  This is a simple
# example that just creates a user acct.  This playbook
# can be extended to do more detailed configuration.

- name: "Configure Instance"
  hosts: all
  become: true
  gather_facts: true

  tasks:

    - name: "Ensure User Account Exists"
      user:
        name: "{{ siduser }}"
        groups: adm

    - name: "Add Authorized Key"
      authorized_key:
        user: "{{ siduser }}"
        key: "{{ lookup('file', '~/.ssh/ssh-key.pub') }}"

    - name: "Install a few sample packages"
      package:
        name:
          - git
          - vim
          - wget
        state: present
...
----



. After reviewing the files we want to begin by executing the intial play defined in _create.yaml_.
+
[source,bash]
[subs="verbatim,attributes"]
----
$> ansible-playbook create.yaml
----
+
If the play is successful you will see output as the playbook executes ending with something similar to the following:
+
[source,ansible]
----
...

TASK [debug] ******************************************************************************************************
ok: [localhost] => {
    "msg": "siduser298-lab1 == Private IP: 172.31.36.33, Public IP: 18.189.29.52"
}

PLAY RECAP ******************************************************************************************************
localhost                  : ok=4    changed=2    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
----
+
The debug statement returns the public and private IPs of the newly created host which has also been written to the inv.txt local inventory file mentioned above.

. Now that the host is available the _configure.yaml_ play can be run to make the instance slightly more useful.
Execute the _configure.yaml_ play with the following command using the `-i` flag to specify the _inv.txt_ as the inventory source for this _Ansible_ run:
+
[source,bash]
[subs="verbatim,attributes"]
----
$> ansible-playbook configure.yaml -i inv.txt
----
+
It may be possible that not all tasks complete successfully. In this case you may see output like the following:
+
[source,ansible]
[subs="verbatim,attributes"]
----
TASK [Install a few sample packages] ****************************************************************************
fatal: [ec2-13-58-174-200.us-east-2.compute.amazonaws.com]: FAILED! => {"changed": false, "msg": "No package matching 'cowsay' found available, installed or updated", "rc": 126, "results": ["No package matching 'cowsay' found available, installed or updated"]}

PLAY RECAP ****************************************************************************
ec2-13-58-174-200.us-east-2.compute.amazonaws.com : ok=3    changed=2    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
----
In this example we can see that 3 tasks were executed, 2 were sucessful, and 1 failed.
The output for the _Install a few sample packages_ task shows that there was no Cowsay package available for that host.

. Now connect to the host by executing the _login_ shell script in the lab1 directory.
+
[source,bash]
[subs="verbatim,attributes"]
----
$> ./login
----


. Finally, run the _clean.yaml_ play to destroy the ec2 instances and clean

